name: Test (Debian)

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  install:
    name: debian12
    runs-on: ubuntu-latest
    container:
      image: debian:12
    steps:
      - uses: actions/checkout@v4

      - name: Install sudo
        run: |
          apt-get update -y
          apt-get install -y sudo

      - name: install.sh (first run)
        run: NONINTERACTIVE=1 ./install.sh

      - name: install.sh (idempotency check)
        run: NONINTERACTIVE=1 ./install.sh
